LOCAL_PATH := $(call my-dir)

include $(CLEAR_VARS)

LOCAL_MODULE_TAGS := optional

LOCAL_MODULE := OSMAnd

# LOCAL_CERTIFICATE := < desired key >

# Use OSMAND_APK_PATH if set. Need to export OSMAND_APK_PATH
ifdef OSMAND_APK_PATH
LOCAL_SRC_FILES := $(OSMAND_APK_PATH)
else
LOCAL_SRC_FILES := osmand.apk
endif

LOCAL_MODULE_CLASS := APPS
LOCAL_OVERRIDES_PACKAGES := Maps

LOCAL_MODULE_SUFFIX := $(COMMON_ANDROID_PACKAGE_SUFFIX)

include $(BUILD_PREBUILT)
